name: Lint

on:
  push:
    branches: ["master"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["master"]
#  schedule:
#    - cron: "37 9 * * 4"

jobs:
  Lint:
    name: Run Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install
        run: npm ci

      - name: Run Lint
        run: npm run lint
