# https://github.com/SilentVoid13/Templater/blob/master/.github/workflows/release.yml
name: Plugin release
on:
  workflow_dispatch:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      attestations: write
    steps:
      - uses: actions/checkout@v7
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
      - name: npm build
        run: |
          npm ci
          npm run build --if-present
      - name: Generate artifact attestations
        uses: actions/attest@v4
        with:
          subject-path: |
            dist/main.js
            dist/styles.css
      - name: Plugin release
        uses: ncipollo/release-action@v1.21.0
        with:
          artifacts: "dist/**/*"
          generateReleaseNotes: true
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
