# https://github.com/SilentVoid13/Templater/blob/master/.github/workflows/release.yml
name: Plugin release
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: npm build
        run: |
          npm install
          npm run build --if-present
      - name: Plugin release
        uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: "dist/**/*"
          generate_release_notes: "true"
          token: ${{ secrets.GITHUB_TOKEN }}
